PROXY_FILE = "artifacts/api-server/src/routes/r2proxy.ts"
with open(PROXY_FILE, "w", encoding="utf-8") as f:
    f.write(
        'import { Router, Request, Response } from "express";\n'
        'import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";\n'
        'import { Readable } from "stream";\n\n'
        'const router = Router();\n\n'
        'function getClient(): S3Client {\n'
        '  return new S3Client({\n'
        '    region: "auto",\n'
        '    endpoint: `https://${process.env.CLOUDFLARE_R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,\n'
        '    credentials: {\n'
        '      accessKeyId: process.env.CLOUDFLARE_R2_ACCESS_KEY_ID!,\n'
        '      secretAccessKey: process.env.CLOUDFLARE_R2_SECRET_ACCESS_KEY!,\n'
        '    },\n'
        '  });\n'
        '}\n\n'
        'router.use(async (req: Request, res: Response): Promise<void> => {\n'
        '  const key = req.path.replace(/^\\//, "");\n'
        '  if (!key) { res.status(400).json({ error: "No key" }); return; }\n'
        '  try {\n'
        '    const cmd = new GetObjectCommand({\n'
        '      Bucket: process.env.CLOUDFLARE_R2_BUCKET_NAME!,\n'
        '      Key: key,\n'
        '    });\n'
        '    const obj = await getClient().send(cmd);\n'
        '    res.setHeader("Content-Type", obj.ContentType ?? "image/jpeg");\n'
        '    res.setHeader("Cache-Control", "public, max-age=31536000, immutable");\n'
        '    (obj.Body as Readable).pipe(res);\n'
        '  } catch {\n'
        '    res.status(404).json({ error: "Not found" });\n'
        '  }\n'
        '});\n\n'
        'export default router;\n'
    )
print("[OK] fix r2proxy.ts pakai router.use()")
